repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: python
        entry: flake8
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        entry: mypy
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        entry: isort
        types: [python]